import { ArrowRight, BookOpen, Camera, ChevronRight, FlaskConical, Heart, MapPinned, Mic2, Users, type LucideIcon } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import Header from './components/Header';
import Atlas from './components/Atlas';
import ContributionModal from './components/ContributionModal';
import Gallery from './components/Gallery';
import MemoriesArchive from './components/MemoriesArchive';
import MemoryModal from './components/MemoryModal';
import MemoryStory from './components/MemoryStory';
import ProjectPage from './components/ProjectPage';
import Login from './components/Login';
import Admin from './components/Admin';
import { cities as seedCities } from './data/cities';
import { memories as seedMemories } from './data/memories';
import type { City, Memory, Place } from './types';
import { api } from './services/api';
import { getLocalContributions } from './services/storage';

type Route = {name:'home'|'atlas'|'projeto'|'galeria'|'memorias'|'login'|'admin'|'memory'|'place'; id?:number};
function route():Route{const h=window.location.hash.replace(/^#/,'');if(h.startsWith('memoria/'))return {name:'memory',id:Number(h.split('/')[1])};if(h.startsWith('local/'))return {name:'place',id:Number(h.split('/')[1])};return {name:(h||'home') as Route['name']};}
export default function App(){const [r,setR]=useState(route()),[cities,setCities]=useState<City[]>(seedCities),[memories,setMemories]=useState<Memory[]>(seedMemories),[places,setPlaces]=useState<Place[]>([]),[contribute,setContribute]=useState(false),[coords,setCoords]=useState<{lat:number,lng:number}|null>(null),[selected,setSelected]=useState<Memory|null>(null),[adminToken,setAdminToken]=useState(localStorage.getItem('mqcd_admin_token')||'');
 useEffect(()=>{const f=()=>{const next=route();setR(next);window.setTimeout(()=>{if(['atlas','projeto','galeria','memorias'].includes(next.name))document.getElementById(next.name)?.scrollIntoView({behavior:'smooth',block:'start'});else window.scrollTo({top:0})},20)};window.addEventListener('hashchange',f);f();return()=>window.removeEventListener('hashchange',f)},[]);
 useEffect(()=>{(async()=>{try{const [c,p,m]=await Promise.all([api.cities(),api.places(),api.memories()]);if(c.length)setCities(c);if(p.length)setPlaces(p);if(m.length)setMemories(m)}catch{}})()},[]);
 useEffect(()=>{const f=(e:Event)=>{const id=(e as CustomEvent).detail;const m=memories.find(x=>x.id===id);if(m){setSelected(null);window.location.hash=`memoria/${m.id}`}};window.addEventListener('open-memory',f);return()=>window.removeEventListener('open-memory',f)},[memories]);
 const community=getLocalContributions().filter(x=>x.status==='Aprovado') as Memory[]; const allMemories=useMemo(()=>[...memories,...community.filter(c=>!memories.some(m=>m.id===c.id))],[memories,community]);
 const openMemory=(m:Memory)=>{setSelected(m)}; const openFull=(m:Memory)=>{setSelected(null);window.location.hash=`memoria/${m.id}`}; const openContribute=(c?:{lat:number,lng:number})=>{setCoords(c||null);setContribute(true)};
 if(r.name==='login')return <Login onBack={()=>window.location.hash=''} onSuccess={t=>{setAdminToken(t);window.location.hash='admin'}}/>;
 if(r.name==='admin')return adminToken?<Admin token={adminToken} onExit={()=>{localStorage.removeItem('mqcd_admin_token');setAdminToken('');window.location.hash=''}}/>:<Login onBack={()=>window.location.hash=''} onSuccess={t=>{setAdminToken(t);window.location.hash='admin'}}/>;
 if(r.name==='memory'){const m=allMemories.find(x=>x.id===r.id);if(!m){window.location.hash='memorias';return null}return <><Header onContribute={()=>openContribute()}/><MemoryStory memory={m} city={cities.find(c=>c.id===m.cityId)} related={allMemories.filter(x=>x.cityId===m.cityId&&x.id!==m.id)} onBack={()=>window.location.hash='memorias'}/></>}
 if(r.name==='place'){const p=places.find(x=>x.id===r.id);return <><Header onContribute={()=>openContribute()}/><section className="place-page"><span className="eyebrow">03 · DETALHE DE LOCAL / LUGAR</span><h1>{p?.name||'Lugar do Atlas'}</h1><p>{p?.description||'Lugar cadastrado no recorte territorial do Atlas.'}</p><div className="place-card"><strong>{p?.kind}</strong><span>{p&&cities.find(c=>c.id===p.cityId)?.name}</span><span>{p?.lat.toFixed(5)}, {p?.lng.toFixed(5)}</span><button className="button primary" onClick={()=>openContribute(p?{lat:p.lat,lng:p.lng}:undefined)}>Registrar memória neste lugar</button></div></section></>}
 return <div><Header onContribute={()=>openContribute()}/><main><Home onAtlas={()=>window.location.hash='atlas'} onProject={()=>window.location.hash='projeto'} onContribute={()=>openContribute()}/><Atlas cities={cities} memories={allMemories} places={places} onOpenMemory={openMemory} onContribute={openContribute}/><ProjectPage cities={cities}/><Gallery/><MemoriesArchive cities={cities} memories={allMemories} onOpen={openMemory}/><section className="contribute-banner"><div><span className="eyebrow">08 · PARTICIPAÇÃO</span><h2>Uma história também pode mudar<br/>a forma como vemos um lugar.</h2></div><button className="button dark" onClick={()=>openContribute()}>Registrar uma memória <ArrowRight/></button></section></main><footer className="footer"><div className="footer-logo"><div>✺</div><span>MEMÓRIAS QUE<br/>CONSTROEM DEMOCRACIA</span></div><p>Atlas Histórico Participativo do Sertão Cearense<br/><span>Ciência · Cidadania · Convivência Democrática</span></p><a href="#login">Área da equipe</a></footer>{selected&&<MemoryModal memory={selected} city={cities.find(c=>c.id===selected.cityId)} onClose={()=>setSelected(null)} onOpen={()=>openFull(selected)}/>} {contribute&&<ContributionModal cities={cities} coords={coords} onClose={()=>setContribute(false)} onSubmitted={()=>{}}/>}</div>}
function Home({onAtlas,onProject,onContribute}:{onAtlas:()=>void;onProject:()=>void;onContribute:()=>void}){return <><section className="hero"><div className="hero-overlay"/><div className="hero-content"><span className="hero-kicker">MEMÓRIA <i>•</i> TERRITÓRIO <i>•</i> PARTICIPAÇÃO</span><h1>Memórias que<br/><em>Constroem Democracia</em></h1><p>Um Atlas Histórico Participativo do Sertão Cearense, construído a partir das histórias, memórias e experiências de quem vive o território.</p><div className="hero-actions"><button className="button primary" onClick={onAtlas}>Explorar o Atlas <ArrowRight/></button><button className="button ghost" onClick={onProject}>Conhecer o projeto</button></div></div><div className="hero-cities">{['Acopiara','Catarina','Deputado Irapuan Pinheiro','Piquet Carneiro'].map((c,i)=><button key={c} onClick={onAtlas}><b>0{i+1}</b>{c}</button>)}</div></section><section className="intro-section"><div className="intro-art"><div className="art-card art-one"><span>01</span><MapPinned/><strong>Território</strong><small>onde as histórias acontecem</small></div><div className="art-card art-two"><span>02</span><Heart/><strong>Memória</strong><small>o que merece ser lembrado</small></div><div className="art-card art-three"><span>03</span><Users/><strong>Participação</strong><small>quem constrói o conhecimento</small></div></div><div className="intro-copy"><span className="eyebrow">01 · UM TERRITÓRIO, MUITAS MEMÓRIAS</span><h2>O mapa também pode<br/><em>contar histórias.</em></h2><p>Este projeto transforma o território em um arquivo vivo e coletivo, aproximando memória, história, cartografia, ciência e participação.</p><button className="text-link" onClick={onAtlas}>Conheça o Atlas <ChevronRight/></button></div></section><section className="statement"><div><span>CIÊNCIA · CIDADANIA · CONVIVÊNCIA DEMOCRÁTICA</span><h2>Conhecimento também<br/><em>é participação.</em></h2><p>Ciência, tecnologia e memória podem caminhar juntas quando o conhecimento está a serviço da vida coletiva.</p><button className="button primary" onClick={onContribute}>Contribua com o Atlas</button></div></section><section className="process-section"><span className="eyebrow">COMO CONSTRUÍMOS</span><h2>Do território ao Atlas.</h2><p>Uma experiência que une pesquisa científica e conhecimento vivido.</p><div className="process-grid">{([['01','Pesquisa',BookOpen],['02','Cartografia',MapPinned],['03','Cartografia social',Users],['04','Trabalho de campo',Camera],['05','Entrevistas',Mic2],['06','Oficinas',FlaskConical]] as [string,string,LucideIcon][]).map(([n,t,I])=><article className="process-card" key={String(n)}><span>{n}</span><I/><h3>{String(t)}</h3></article>)}</div></section></>}
