import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import multer from 'multer';
import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import { fileURLToPath } from 'url';
import pg from 'pg';

dotenv.config();
const __dirname=path.dirname(fileURLToPath(import.meta.url));
const root=path.resolve(__dirname,'..');
const dbDir=path.join(root,'db'); const dbFile=path.join(dbDir,'local-data.json'); const uploadDir=path.join(root,'uploads');
fs.mkdirSync(dbDir,{recursive:true});fs.mkdirSync(uploadDir,{recursive:true});
const citiesSeed=[
 {id:1,name:'Acopiara',ibgeCode:'2300309',description:'Parte do recorte territorial do Atlas.',center:[-6.0936,-39.4543],zoom:13,color:'#FE5300',neighborhoods:['Centro','Vila Esperança','Nova Acopiara','São Francisco','Moreiras','Vila Palmeira','Vila São João','Quincoé','Santa Felícia','Santo Antônio','São Paulinho','Trussu','Isidoro','Ebron','Barra do Ingá','Solidão'],localities:['Trussu','Quincoé','Santa Felícia','Isidoro','Ebron']},
 {id:2,name:'Catarina',ibgeCode:'2303600',description:'Município dos Inhamuns integrado ao Atlas.',center:[-6.135,-39.8762],zoom:13,color:'#8E1B75',neighborhoods:['Centro','Vila Macário','Vila Nova','Vila Balanças','Lagoinha','Vila Holanda'],localities:['São Gonçalo']},
 {id:3,name:'Deputado Irapuan Pinheiro',ibgeCode:'2304269',description:'Território de pesquisa, campo e cartografia social.',center:[-5.9174,-39.2672],zoom:13,color:'#267082',neighborhoods:['Centro','Aurora','Maratoã','Monte Sinai','Velame'],localities:['Baixio','Betânia','Velame']},
 {id:4,name:'Piquet Carneiro',ibgeCode:'2310902',description:'Município integrado ao recorte inicial do Atlas.',center:[-5.80025,-39.41702],zoom:13,color:'#71863A',neighborhoods:['Alto Alegre','Piquezinho','Rancho Verde','Centro','Cidade Nova','Bumerangue','Alto dos Maias','João Paulo II','Alto do Bem-ti-vi','Cruzeiro','Santa Luzia'],localities:['Ibicuã','Mulungu','Catolé da Pista','Baixio']}
];
const seedMemories=[
 {id:1,title:'Monte Mor',cityId:1,neighborhood:'Zona rural / área de campo',category:'Cultura',period:'09 de maio',story:'Registro editorial do trabalho de campo realizado no Monte Mor, em Acopiara. Ficha preparada para receber a narrativa final, fotografias, entrevistas e documentos.',contributor:'Equipe do projeto',lat:-6.0936,lng:-39.4543,status:'Aprovado',demo:true,featured:true,createdAt:'2026-05-09T12:00:00Z'},
 {id:2,title:'Trilha dos Caldeirões',cityId:3,neighborhood:'Zona rural',category:'Patrimônio',period:'11 de junho',story:'Registro editorial da atividade realizada na Trilha dos Caldeirões, em Deputado Irapuan Pinheiro. Ficha preparada para descrição final, imagens, vídeos e relatos.',contributor:'Equipe do projeto',lat:-5.9174,lng:-39.2672,status:'Aprovado',demo:true,featured:true,createdAt:'2026-06-11T12:00:00Z'},
 {id:3,title:'Memória do Centro',cityId:2,neighborhood:'Centro',category:'Memória',period:'Registro inicial',story:'Ficha inicial para reunir uma memória urbana de Catarina. O conteúdo definitivo deve ser substituído pelos registros documentados nas entrevistas e oficinas.',contributor:'Equipe do projeto',lat:-6.135,lng:-39.8762,status:'Aprovado',demo:true,createdAt:'2026-06-20T12:00:00Z'},
 {id:4,title:'Paisagens de Piquet Carneiro',cityId:4,neighborhood:'Centro',category:'Fotografia',period:'Registro inicial',story:'Ficha inicial para uma coleção fotográfica de Piquet Carneiro. Use o formulário do Atlas para acrescentar registros documentais da comunidade.',contributor:'Equipe do projeto',lat:-5.80025,lng:-39.41702,status:'Aprovado',demo:true,createdAt:'2026-06-20T12:00:00Z'}
];
function makePlaces(){const offsets=[[-.025,-.035],[.018,.02],[-.01,.045],[.032,-.015],[-.038,.012],[.006,-.052],[.042,.04],[-.048,-.03]];let id=1;const out=[];for(const c of citiesSeed){const names=[...c.neighborhoods,...c.localities];names.forEach((name,i)=>{const o=offsets[i%offsets.length];out.push({id:id++,cityId:c.id,name,kind:i<c.neighborhoods.length?'Bairro':'Localidade',lat:c.center[0]+o[0],lng:c.center[1]+o[1],description:'Ponto cadastrado como base inicial editável do Atlas.'})})}return out}
function fresh(){return {cities:citiesSeed,places:makePlaces(),memories:seedMemories,contributions:[],interviews:[]}}
if(!fs.existsSync(dbFile) || !readableSeedFile()) fs.writeFileSync(dbFile,JSON.stringify(fresh(),null,2));
function readDb(){try{return JSON.parse(fs.readFileSync(dbFile,'utf8'))}catch{return fresh()}}
function readableSeedFile(){try{const x=JSON.parse(fs.readFileSync(dbFile,'utf8'));return Array.isArray(x.cities)&&x.cities.length>0}catch{return false}}
function writeDb(db){fs.writeFileSync(dbFile,JSON.stringify(db,null,2))}
const usePg=Boolean(process.env.DATABASE_URL);const pool=usePg?new pg.Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL.includes('supabase')?{rejectUnauthorized:false}:undefined}):null;
const app=express();app.use(cors());app.use(express.json({limit:'10mb'}));app.use('/uploads',express.static(uploadDir));
const upload=multer({storage:multer.diskStorage({destination:(_,__,cb)=>cb(null,uploadDir),filename:(_,file,cb)=>cb(null,`${Date.now()}-${crypto.randomBytes(4).toString('hex')}${path.extname(file.originalname)}`)}),limits:{fileSize:50*1024*1024}});
function admin(req,res,next){const key=req.headers['x-admin-key'];if(key!== (process.env.ADMIN_KEY||'atlas-demo-2026'))return res.status(401).json({error:'Acesso restrito à equipe.'});next()}
app.get('/api/health',async(_,res)=>res.json({ok:true,database:usePg?'PostgreSQL':'JSON local',message:'Memórias que Constroem Democracia API'}));
app.get('/api/cities',async(_,res)=>{if(pool){const {rows}=await pool.query('SELECT * FROM cities ORDER BY id');return res.json(rows)}res.json(readDb().cities)});
app.get('/api/places',async(req,res)=>{if(pool){const p=[];let sql='SELECT * FROM places';if(req.query.city_id){p.push(req.query.city_id);sql+=' WHERE city_id=$1'}sql+=' ORDER BY name';const {rows}=await pool.query(sql,p);return res.json(rows)}let a=readDb().places;if(req.query.city_id)a=a.filter(x=>x.cityId===Number(req.query.city_id));res.json(a)});
app.get('/api/memories',async(req,res)=>{if(pool){const p=[];const w=["status='Aprovado'"];if(req.query.city_id){p.push(req.query.city_id);w.push(`city_id=$${p.length}`)}if(req.query.category){p.push(req.query.category);w.push(`category=$${p.length}`)}if(req.query.q){p.push(`%${req.query.q}%`);w.push(`(title ILIKE $${p.length} OR story ILIKE $${p.length} OR neighborhood ILIKE $${p.length})`)}const {rows}=await pool.query(`SELECT * FROM memories WHERE ${w.join(' AND ')} ORDER BY featured DESC,created_at DESC`,p);return res.json(rows)}let a=readDb().memories.filter(x=>x.status==='Aprovado');if(req.query.city_id)a=a.filter(x=>x.cityId===Number(req.query.city_id));if(req.query.category)a=a.filter(x=>x.category===req.query.category);if(req.query.q){const q=String(req.query.q).toLowerCase();a=a.filter(x=>`${x.title} ${x.story} ${x.neighborhood}`.toLowerCase().includes(q))}res.json(a)});
app.post('/api/contributions',upload.array('files',20),async(req,res)=>{const {title,story,city_id,neighborhood,category,period,contributor,email,lat,lng,authorization}=req.body;if(!authorization)return res.status(400).json({error:'Autorização obrigatória.'});const files=(req.files||[]).map(f=>({name:f.originalname,url:`/uploads/${f.filename}`,mime:f.mimetype}));if(pool){const r=await pool.query(`INSERT INTO contributions(title,story,city_id,neighborhood,category,period,contributor,email,lat,lng,authorization,files) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING id,status,created_at`,[title,story,city_id,neighborhood,category,period||'',contributor,email||null,Number(lat),Number(lng),true,JSON.stringify(files)]);return res.status(201).json(r.rows[0])}const db=readDb();const c={id:Date.now(),title,story,cityId:Number(city_id),neighborhood,category,period:period||'',contributor,email:email||'',lat:Number(lat),lng:Number(lng),authorization:true,status:'Pendente',submittedAt:new Date().toISOString(),files};db.contributions.unshift(c);writeDb(db);res.status(201).json({id:c.id,status:c.status})});
app.post('/api/auth/login',(req,res)=>{const email=process.env.ADMIN_EMAIL||'admin@atlas.local';const password=process.env.ADMIN_PASSWORD||'atlas2026';if(req.body.email!==email||req.body.password!==password)return res.status(401).json({error:'E-mail ou senha inválidos.'});res.json({token:process.env.ADMIN_KEY||'atlas-demo-2026',user:{email,name:'Equipe do Atlas'}})});
app.get('/api/admin/contributions',admin,async(_,res)=>{if(pool){const {rows}=await pool.query('SELECT * FROM contributions ORDER BY created_at DESC');return res.json(rows)}res.json(readDb().contributions)});
app.patch('/api/admin/contributions/:id',admin,async(req,res)=>{const allowed=['Pendente','Em análise','Aprovado','Recusado'];if(!allowed.includes(req.body.status))return res.status(400).json({error:'Status inválido.'});if(pool){const {rows}=await pool.query('UPDATE contributions SET status=$1,updated_at=NOW() WHERE id=$2 RETURNING *',[req.body.status,req.params.id]);if(!rows[0])return res.status(404).json({error:'Contribuição não encontrada.'});if(req.body.status==='Aprovado')await pool.query(`INSERT INTO memories(title,story,city_id,neighborhood,category,period,contributor,lat,lng,status,created_at) SELECT title,story,city_id,neighborhood,category,period,contributor,lat,lng,'Aprovado',NOW() FROM contributions WHERE id=$1 AND NOT EXISTS (SELECT 1 FROM memories WHERE title=contributions.title AND city_id=contributions.city_id)`,[req.params.id]);return res.json(rows[0])}const db=readDb();const c=db.contributions.find(x=>String(x.id)===String(req.params.id));if(!c)return res.status(404).json({error:'Contribuição não encontrada.'});c.status=req.body.status;c.updatedAt=new Date().toISOString();if(c.status==='Aprovado'&&!db.memories.some(m=>m.id===c.id)){db.memories.unshift({...c,createdAt:new Date().toISOString()})}writeDb(db);res.json(c)});
app.get('/api/stats',async(_,res)=>{if(pool){const [m,p,i,c]=await Promise.all([pool.query("SELECT COUNT(*)::int count FROM memories WHERE status='Aprovado'"),pool.query('SELECT COUNT(*)::int count FROM places'),pool.query('SELECT COUNT(*)::int count FROM interviews'),pool.query('SELECT COUNT(*)::int count FROM contributions')]);return res.json({cities:4,memories:m.rows[0].count,places:p.rows[0].count,interviews:i.rows[0].count,contributions:c.rows[0].count})}const db=readDb();res.json({cities:db.cities.length,memories:db.memories.filter(x=>x.status==='Aprovado').length,places:db.places.length,interviews:db.interviews.length,contributions:db.contributions.length})});
const port=Number(process.env.PORT||3001);app.listen(port,()=>console.log(`API em http://localhost:${port} · banco: ${usePg?'PostgreSQL':'JSON local'}`));
