import { CheckCircle2, FileUp, MapPin, X } from 'lucide-react';
import { useState, type FormEvent } from 'react';
import type { Category, City } from '../types';
import { api } from '../services/api';
import { saveLocalContribution } from '../services/storage';

const categories:Category[]=['Memória','Patrimônio','História','Cultura','Comunidade','Fotografia','Vídeo','Educação'];
export default function ContributionModal({cities,coords,onClose,onSubmitted}:{cities:City[];coords:{lat:number,lng:number}|null;onClose:()=>void;onSubmitted:()=>void}){
 const [cityId,setCityId]=useState(''),[category,setCategory]=useState<Category>('Memória'),[neighborhood,setNeighborhood]=useState(''),[sent,setSent]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const current=cities.find(c=>c.id===Number(cityId));
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');setLoading(true);const form=e.currentTarget;const fd=new FormData(form);fd.set('city_id',cityId);fd.set('category',category);fd.set('neighborhood',neighborhood);fd.set('lat',String(coords?.lat??current?.center[0]??0));fd.set('lng',String(coords?.lng??current?.center[1]??0));fd.set('authorization','true');try{await api.contribute(fd)}catch{const now=new Date().toISOString();saveLocalContribution({id:Date.now(),title:String(fd.get('title')||''),story:String(fd.get('story')||''),cityId:Number(cityId),neighborhood,category,period:String(fd.get('period')||''),contributor:String(fd.get('contributor')||''),email:String(fd.get('email')||''),lat:Number(fd.get('lat')),lng:Number(fd.get('lng')),status:'Pendente',submittedAt:now,authorization:true});}finally{setLoading(false);setSent(true);onSubmitted()}}
 if(sent)return <div className="modal-backdrop"><article className="success-card"><div className="success-icon"><CheckCircle2/></div><span className="eyebrow">REGISTRO RECEBIDO</span><h2>Sua memória entrou no Atlas.</h2><p>Ela ficará <strong>pendente de análise</strong> até que a equipe responsável avalie texto, localização e arquivos enviados.</p><button className="button primary" onClick={onClose}>Voltar ao Atlas</button></article></div>;
 return <div className="modal-backdrop" onMouseDown={onClose}><article className="form-modal contribution-modal" onMouseDown={e=>e.stopPropagation()}><button className="close-button" onClick={onClose}><X/></button><div className="form-header"><span className="eyebrow">CONTRIBUIR / REGISTRAR MEMÓRIA</span><h2>Compartilhe sua memória</h2><p>Cada história importa. Registre um lugar, uma lembrança, uma foto ou um vídeo e ajude a construir este Atlas.</p></div>{coords&&<div className="selected-location"><MapPin/> Ponto escolhido no mapa: {coords.lat.toFixed(5)}, {coords.lng.toFixed(5)}</div>}
 <form onSubmit={submit}><div className="type-grid">{categories.slice(0,4).map(c=><button type="button" key={c} className={category===c?'active':''} onClick={()=>setCategory(c)}><span>{c==='Memória'?'◉':c==='Foto'?'▣':'✦'}</span>{c}</button>)}</div><label>Título da memória<input name="title" required placeholder="Ex.: A festa da minha infância"/></label><label>Descrição / narrativa<textarea name="story" required rows={5} placeholder="Conte o que aconteceu, quem participou e por que este lugar é importante..."/></label><div className="form-grid"><label>Cidade<select required value={cityId} onChange={e=>{setCityId(e.target.value);setNeighborhood('')}}><option value="">Selecione a cidade</option>{cities.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Categoria<select value={category} onChange={e=>setCategory(e.target.value as Category)}>{categories.map(c=><option key={c}>{c}</option>)}</select></label></div><label>Bairro / localidade<select required value={neighborhood} onChange={e=>setNeighborhood(e.target.value)}><option value="">Selecione</option>{current?.neighborhoods.map(n=><option key={n}>{n}</option>)}{current?.localities.map(n=><option key={n}>{n} — localidade</option>)}</select></label><div className="form-grid"><label>Período<input name="period" placeholder="Ex.: década de 1990"/></label><label>Seu nome<input name="contributor" required placeholder="Como devemos identificar você?"/></label></div><label>E-mail <span>(opcional)</span><input name="email" type="email" placeholder="seuemail@email.com"/></label><label className="upload"><FileUp/><span>Fotos, vídeos ou documentos</span><input name="files" type="file" multiple accept="image/*,video/*,.pdf,.doc,.docx"/></label><label className="checkbox"><input required type="checkbox"/> Autorizo o uso deste material no projeto, conforme as condições de participação.</label>{error&&<div className="form-error">{error}</div>}<button className="button primary full" disabled={loading}>{loading?'ENVIANDO...':'ENVIAR CONTRIBUIÇÃO'}</button></form></article></div>
}
